import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseStl } from "../src/core/parse-stl.js";
import { parseObj } from "../src/core/parse-obj.js";
import { buildAdjacency } from "../src/core/adjacency.js";
import { computeDihedralWeights } from "../src/core/dihedral.js";
import { buildSpanningTree } from "../src/core/spanning-tree.js";
import { buildLayout } from "../src/core/flatten.js";
import { emitSvg } from "../src/core/emit-svg.js";
import { detectOverlaps } from "../src/core/overlap.js";

/**
 * Run the unfolding pipeline over every mesh in test/corpus/ and
 * record a baseline: pipeline completion plus the count of
 * overlapping face pairs from the canonical `detectOverlaps` stage.
 */

const here = dirname(fileURLToPath(import.meta.url));
const corpusDir = join(here, "..", "test", "corpus");
const outputPath = join(here, "..", "docs", "baseline-pipeline.md");

const entries = readdirSync(corpusDir, { withFileTypes: true })
  .filter((e) => e.isFile())
  .map((e) => e.name)
  .filter((n) => {
    const ext = extname(n).toLowerCase();
    return ext === ".stl" || ext === ".obj";
  })
  .sort();

type Result = {
  model: string;
  format: string;
  faces: string;
  pipeline: string;
  overlaps: string;
};

const results: Result[] = [];

for (const fname of entries) {
  const ext = extname(fname).toLowerCase();
  const contents = readFileSync(join(corpusDir, fname), "utf8");
  const r: Result = {
    model: fname,
    format: ext.slice(1),
    faces: "—",
    pipeline: "completed",
    overlaps: "—",
  };

  let mesh;
  try {
    mesh = ext === ".stl" ? parseStl(contents) : parseObj(contents);
    r.faces = String(mesh.faces.length);
  } catch {
    r.pipeline = "failed at parse";
    results.push(r);
    continue;
  }

  let dual;
  try {
    dual = buildAdjacency(mesh);
  } catch {
    r.pipeline = "failed at buildAdjacency";
    results.push(r);
    continue;
  }

  let weights;
  try {
    weights = computeDihedralWeights(mesh, dual);
  } catch {
    r.pipeline = "failed at computeDihedralWeights";
    results.push(r);
    continue;
  }

  let tree;
  try {
    tree = buildSpanningTree(dual, weights);
  } catch {
    r.pipeline = "failed at buildSpanningTree";
    results.push(r);
    continue;
  }

  let layout;
  try {
    layout = buildLayout(mesh, tree);
  } catch {
    r.pipeline = "failed at buildLayout";
    results.push(r);
    continue;
  }

  try {
    emitSvg(layout, tree);
  } catch {
    r.pipeline = "failed at emitSvg";
    results.push(r);
    continue;
  }

  r.overlaps = String(detectOverlaps(layout).length);
  results.push(r);
}

const headers = ["model", "format", "faces", "pipeline", "overlapping face pairs"];
const rows = results.map((r) => [r.model, r.format, r.faces, r.pipeline, r.overlaps]);
const widths = headers.map((h, i) =>
  Math.max(h.length, ...rows.map((row) => row[i].length)),
);
const formatRow = (cells: string[]) =>
  "| " + cells.map((c, i) => c.padEnd(widths[i])).join(" | ") + " |";
const sepRow = "| " + widths.map((w) => "-".repeat(w)).join(" | ") + " |";

const completed = results.filter((r) => r.pipeline === "completed");
const clean = completed.filter((r) => r.overlaps === "0");

const today = new Date().toISOString().slice(0, 10);
const md = [
  "# Pipeline baseline",
  "",
  `Generated by \`scripts/baseline-pipeline.ts\` on ${today}. Re-run with \`pnpm baseline\`.`,
  "",
  formatRow(headers),
  sepRow,
  ...rows.map(formatRow),
  "",
  `**Summary:** ${clean.length} of ${completed.length} models that completed the pipeline produced an overlap-free net.`,
  "",
].join("\n");

writeFileSync(outputPath, md);

console.log(formatRow(headers));
console.log(sepRow);
for (const row of rows) console.log(formatRow(row));
console.log();
console.log(
  `${clean.length} of ${completed.length} models produce overlap-free nets.`,
);
console.log(`\nWrote ${outputPath}`);
