import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseStl } from "../src/core/parse-stl.js";
import { parseObj } from "../src/core/parse-obj.js";
import { buildAdjacency } from "../src/core/adjacency.js";
import { computeDihedralWeights } from "../src/core/dihedral.js";
import { buildSpanningTree } from "../src/core/spanning-tree.js";
import { buildLayout } from "../src/core/flatten.js";
import { emitSvg } from "../src/core/emit-svg.js";
import { detectOverlaps } from "../src/core/overlap.js";
import { recut } from "../src/core/recut.js";
import { buildRenderablePieces } from "../src/core/tabs.js";

/**
 * Run the unfolding pipeline over every mesh in test/corpus/ and
 * record a baseline: pipeline completion, the pre-recut count of
 * overlapping face pairs, and the post-recut piece count. Verifies
 * every piece is internally overlap-free.
 */

const here = dirname(fileURLToPath(import.meta.url));
const corpusDir = join(here, "..", "test", "corpus");
const outputPath = join(here, "..", "docs", "baseline-pipeline.md");

const entries = readdirSync(corpusDir, { withFileTypes: true })
  .filter((e) => e.isFile())
  .map((e) => e.name)
  .filter((n) => {
    const ext = extname(n).toLowerCase();
    return ext === ".stl" || ext === ".obj";
  })
  .sort();

type Result = {
  model: string;
  format: string;
  faces: string;
  pipeline: string;
  overlaps: string;
  pieces: string;
  piecesClean: boolean;
};

const results: Result[] = [];

for (const fname of entries) {
  const ext = extname(fname).toLowerCase();
  const contents = readFileSync(join(corpusDir, fname), "utf8");
  const r: Result = {
    model: fname,
    format: ext.slice(1),
    faces: "—",
    pipeline: "completed",
    overlaps: "—",
    pieces: "—",
    piecesClean: true,
  };

  let mesh;
  try {
    mesh = ext === ".stl" ? parseStl(contents) : parseObj(contents);
    r.faces = String(mesh.faces.length);
  } catch {
    r.pipeline = "failed at parse";
    results.push(r);
    continue;
  }

  let dual;
  try {
    dual = buildAdjacency(mesh);
  } catch {
    r.pipeline = "failed at buildAdjacency";
    results.push(r);
    continue;
  }

  let weights;
  try {
    weights = computeDihedralWeights(mesh, dual);
  } catch {
    r.pipeline = "failed at computeDihedralWeights";
    results.push(r);
    continue;
  }

  let tree;
  try {
    tree = buildSpanningTree(dual, weights);
  } catch {
    r.pipeline = "failed at buildSpanningTree";
    results.push(r);
    continue;
  }

  let layout;
  try {
    layout = buildLayout(mesh, tree);
  } catch {
    r.pipeline = "failed at buildLayout";
    results.push(r);
    continue;
  }

  const overlaps = detectOverlaps(layout);
  r.overlaps = String(overlaps.length);

  try {
    const result = recut(tree, layout, overlaps);
    r.pieces = String(result.pieces.length);
    r.piecesClean = result.pieces.every(
      (p) => detectOverlaps(p.layout).length === 0,
    );
    const renderable = buildRenderablePieces(result);
    for (const piece of renderable) emitSvg(piece);
  } catch {
    r.pipeline = "failed at recut";
    results.push(r);
    continue;
  }

  results.push(r);
}

const headers = [
  "model",
  "format",
  "faces",
  "pipeline",
  "overlaps (pre-recut)",
  "pieces",
];
const rows = results.map((r) => [
  r.model,
  r.format,
  r.faces,
  r.pipeline,
  r.overlaps,
  r.pieces,
]);
const widths = headers.map((h, i) =>
  Math.max(h.length, ...rows.map((row) => row[i].length)),
);
const formatRow = (cells: string[]) =>
  "| " + cells.map((c, i) => c.padEnd(widths[i])).join(" | ") + " |";
const sepRow = "| " + widths.map((w) => "-".repeat(w)).join(" | ") + " |";

const completed = results.filter((r) => r.pipeline === "completed");
const pieceCounts = completed
  .map((r) => Number.parseInt(r.pieces, 10))
  .filter((n) => Number.isFinite(n));
const minPieces = pieceCounts.length ? Math.min(...pieceCounts) : 0;
const maxPieces = pieceCounts.length ? Math.max(...pieceCounts) : 0;
const totalPieces = pieceCounts.reduce((s, n) => s + n, 0);
const dirty = completed.filter((r) => !r.piecesClean);

const today = new Date().toISOString().slice(0, 10);
const summaryLines = [
  `**Summary:** ${completed.length} models completed the pipeline; recut produced ${totalPieces} pieces total (per-model range ${minPieces}–${maxPieces}).`,
];
if (dirty.length === 0) {
  summaryLines.push("Every piece is internally overlap-free.");
} else {
  summaryLines.push(
    `WARNING: piece(s) with internal overlap in: ${dirty.map((r) => r.model).join(", ")}.`,
  );
}

const md = [
  "# Pipeline baseline",
  "",
  `Generated by \`scripts/baseline-pipeline.ts\` on ${today}. Re-run with \`pnpm baseline\`.`,
  "",
  formatRow(headers),
  sepRow,
  ...rows.map(formatRow),
  "",
  ...summaryLines,
  "",
].join("\n");

writeFileSync(outputPath, md);

console.log(formatRow(headers));
console.log(sepRow);
for (const row of rows) console.log(formatRow(row));
console.log();
for (const line of summaryLines) console.log(line.replace(/\*\*/g, ""));
console.log(`\nWrote ${outputPath}`);
